/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Todo } from "./classes/todo/todo.class";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TodoItem {
        "todo": Todo;
    }
    interface TodoItemNew {
    }
    interface TodoList {
    }
}
export interface TodoItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoItemElement;
}
export interface TodoItemNewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoItemNewElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLTodoItemNewElement extends Components.TodoItemNew, HTMLStencilElement {
    }
    var HTMLTodoItemNewElement: {
        prototype: HTMLTodoItemNewElement;
        new (): HTMLTodoItemNewElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "todo-item": HTMLTodoItemElement;
        "todo-item-new": HTMLTodoItemNewElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TodoItem {
        "onTodoChanged"?: (event: TodoItemCustomEvent<Todo>) => void;
        "todo"?: Todo;
    }
    interface TodoItemNew {
        "onTodoCreated"?: (event: TodoItemNewCustomEvent<Todo>) => void;
    }
    interface TodoList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "todo-item": TodoItem;
        "todo-item-new": TodoItemNew;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
            "todo-item-new": LocalJSX.TodoItemNew & JSXBase.HTMLAttributes<HTMLTodoItemNewElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
