/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Todo } from "./classes/todo/todo.class";
export namespace Components {
    interface TodoItem {
        "todo": Todo;
    }
    interface TodoItemNew {
    }
    interface TodoList {
    }
    interface TodoListTitle {
    }
}
export interface TodoItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoItemElement;
}
export interface TodoItemNewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoItemNewElement;
}
declare global {
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLTodoItemNewElement extends Components.TodoItemNew, HTMLStencilElement {
    }
    var HTMLTodoItemNewElement: {
        prototype: HTMLTodoItemNewElement;
        new (): HTMLTodoItemNewElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLTodoListTitleElement extends Components.TodoListTitle, HTMLStencilElement {
    }
    var HTMLTodoListTitleElement: {
        prototype: HTMLTodoListTitleElement;
        new (): HTMLTodoListTitleElement;
    };
    interface HTMLElementTagNameMap {
        "todo-item": HTMLTodoItemElement;
        "todo-item-new": HTMLTodoItemNewElement;
        "todo-list": HTMLTodoListElement;
        "todo-list-title": HTMLTodoListTitleElement;
    }
}
declare namespace LocalJSX {
    interface TodoItem {
        "onTodoDeleted"?: (event: TodoItemCustomEvent<Todo>) => void;
        "onTodoStateChanged"?: (event: TodoItemCustomEvent<Todo>) => void;
        "onTodoTitleChanged"?: (event: TodoItemCustomEvent<Todo>) => void;
        "todo"?: Todo;
    }
    interface TodoItemNew {
        "onTodoCreated"?: (event: TodoItemNewCustomEvent<Todo>) => void;
    }
    interface TodoList {
    }
    interface TodoListTitle {
    }
    interface IntrinsicElements {
        "todo-item": TodoItem;
        "todo-item-new": TodoItemNew;
        "todo-list": TodoList;
        "todo-list-title": TodoListTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
            "todo-item-new": LocalJSX.TodoItemNew & JSXBase.HTMLAttributes<HTMLTodoItemNewElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
            "todo-list-title": LocalJSX.TodoListTitle & JSXBase.HTMLAttributes<HTMLTodoListTitleElement>;
        }
    }
}
